# Generated by Django 3.2.21 on 2023-09-08 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('captures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Captures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface', models.CharField(max_length=255)),
                ('nb_packet', models.IntegerField()),
                ('date_heure', models.DateTimeField()),
                ('fait', models.BooleanField(default=False)),
            ],
        ),
    ]
